export const workdata=[
    {
        roomname:"H1",
        inspector:"Francis",
        cleaner:"William"
    },
    {
        roomname:"H1",
        inspector:"Francis",
        cleaner:"William"
    },
    {
        roomname:"H1",
        inspector:"Francis",
        cleaner:"William"
    },
    {
        roomname:"H1",
        inspector:"Francis",
        cleaner:"William"
    },
    {
        roomname:"H1",
        inspector:"Francis",
        cleaner:"William"
    },
    {
        roomname:"H1",
        inspector:"Francis",
        cleaner:"William"
    },
    {
        roomname:"H1",
        inspector:"Francis",
        cleaner:"William"
    },
    {
        roomname:"H1",
        inspector:"Francis",
        cleaner:"William"
    },
    {
        roomname:"H1",
        inspector:"Francis",
        cleaner:"William"
    },
    {
        roomname:"H1",
        inspector:"Francis",
        cleaner:"William"
    },
    {
        roomname:"H1",
        inspector:"Francis",
        cleaner:"William"
    },
    {
        roomname:"H1",
        inspector:"Francis",
        cleaner:"William"
    },
    {
        roomname:"H1",
        inspector:"Francis",
        cleaner:"William"
    },
    {
        roomname:"H1",
        inspector:"Francis",
        cleaner:"William"
    },
    {
        roomname:"H1",
        inspector:"Francis",
        cleaner:"William"
    },
    {
        roomname:"H1",
        inspector:"Francis",
        cleaner:"William"
    },
]