export const cleandata=[
    {
        id: "728ed52f",
        name: "Anthony",
        phonenumber: "0966789094",
        email: "m@example.com",
      },
      {
          id: "728ed52f",
          name: "Anthony",
          phonenumber: "0966789094",
          email: "m@example.com",
        },
        {
          id: "728ed52f",
          name: "Anthony",
          phonenumber: "0966789094",
          email: "m@example.com",
        },
        {
          id: "728ed52f",
          name: "Anthony",
          phonenumber: "0966789094",
          email: "m@example.com",
        },
        {
          id: "728ed52f",
          name: "Anthony",
          phonenumber: "0966789094",
          email: "m@example.com",
        },
        {
          id: "728ed52f",
          name: "Anthony",
          phonenumber: "0966789094",
          email: "m@example.com",
        },
        {
          id: "728ed52f",
          name: "Anthony",
          phonenumber: "0966789094",
          email: "m@example.com",
        },
        {
            id: "728ed52f",
            name: "Anthony",
            phonenumber: "0966789094",
            email: "m@example.com",
          },
          {
            id: "728ed52f",
            name: "Anthony",
            phonenumber: "0966789094",
            email: "m@example.com",
          },
          {
            id: "728ed52f",
            name: "Anthony",
            phonenumber: "0966789094",
            email: "m@example.com",
          },
          {
            id: "728ed52f",
            name: "Anthony",
            phonenumber: "0966789094",
            email: "m@example.com",
          },
          {
            id: "728ed52f",
            name: "Anthony",
            phonenumber: "0966789094",
            email: "m@example.com",
          },
          {
            id: "728ed52f",
            name: "Anthony",
            phonenumber: "0966789094",
            email: "m@example.com",
          },
          {
            id: "728ed52f",
            name: "Anthony",
            phonenumber: "0966789094",
            email: "m@example.com",
          },
          {
            id: "728ed52f",
            name: "Anthony",
            phonenumber: "0966789094",
            email: "m@example.com",
          },
          {
            id: "728ed52f",
            name: "Anthony",
            phonenumber: "0966789094",
            email: "m@example.com",
          },
          {
            id: "728ed52f",
            name: "Anthony",
            phonenumber: "0966789094",
            email: "m@example.com",
          },
        
]